CREATE DATABASE SIAP;
GO

USE SIAP

CREATE TABLE ROLES (
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Tipo VARCHAR(100),
Descripcion VARCHAR(100)


);

CREATE TABLE USUARIOS (
    Id INT  NOT NULL PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(100),
    Apellido VARCHAR(100),
    Telefono INT,
    Email VARCHAR(100),
    Contraseña VARCHAR(100),
    Rol INT REFERENCES ROLES (Id) ,
    Fecha_nacimiento DATETIME NULL,
    Foto Varchar(100)


);


CREATE TABLE MENSAJES (
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Texto VARCHAR(500),
RemitenteId INT REFERENCES USUARIOS (Id),
DestinatarioId INT REFERENCES USUARIOS (Id),
);

CREATE TABLE MUNICIPIOS (
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Municipio VARCHAR(100)


);

CREATE TABLE PROPIEDADES (
   Id INT  NOT NULL PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(100),
    Direccion VARCHAR(100) ,
    Capacidad INT,
    TipoPropiedad VARCHAR(100),
    Precio DECIMAL (10,2),
    EstanciaMinima VARCHAR(100),
    ReglasPropiedad VARCHAR (500),
    Descripcion VARCHAR(100),
    PoliticasCancelacion VARCHAR(100),
    UsuarioId INT REFERENCES USUARIOS (Id),
    MunicipioId INT REFERENCES MUNICIPIOS (Id),
    Imagen VARCHAR(100)

);


CREATE TABLE BUSQUEDAS (
Id INT  NOT NULL PRIMARY KEY IDENTITY(1,1),
Decha_deseada DATETIME null,
Fecha_fin DATETIME null,
Cantidad_huesped  int null,
Ciudad VARCHAR(100) null,
Precio_min DECIMAL (10,2) null,
Precio_max DECIMAL (10,2) null,
TipoPropiedad NVARCHAR(50) null,
UsuarioId INT REFERENCES USUARIOS (Id)
);

CREATE TABLE ESTADOS(
id INT  NOT NULL PRIMARY KEY IDENTITY(1,1),
tipo VARCHAR (100)
);

CREATE TABLE RESERVAS(
Id INT  NOT NULL PRIMARY KEY IDENTITY(1,1),
Fecha_creacion DATETIME,
Fecha_deseada DATETIME,
Fecha_fin DATETIME,
Cantidad_huesped INT,
Costo_total DECIMAL (10,2),
UsuarioId INT REFERENCES USUARIOS (Id),
PropiedadId INT REFERENCES PROPIEDADES (Id),
EstadoId INT REFERENCES ESTADOS (Id)

);

CREATE TABLE PAGOS(
Id INT  NOT NULL PRIMARY KEY IDENTITY(1,1),
UsuarioId INT REFERENCES USUARIOS (Id),
Codigo VARCHAR(100),
Monto DECIMAL(10,2),
Metodo VARCHAR(100),
ReservaId INT REFERENCES RESERVAS(Id),
Fecha_pago DATETIME
);



CREATE TABLE RESENAS(
Id INT  NOT NULL PRIMARY KEY IDENTITY(1,1),
Fecha_creacion DATETIME,
Comentario VARCHAR(200),
Clasificacion int,
PropiedadId INT REFERENCES PROPIEDADES (Id),
ReservaId INT REFERENCES RESERVAS (Id)

);